// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3eteFOnIkiuByIRkYe97WbzWwYXXp3YU',
    appId: '1:317214982580:web:f97da1a3bf03f1f21172e1',
    messagingSenderId: '317214982580',
    projectId: 'plantdisease-e827d',
    authDomain: 'plantdisease-e827d.firebaseapp.com',
    storageBucket: 'plantdisease-e827d.firebasestorage.app',
    measurementId: 'G-Y8HHNJKYDS',
    databaseURL: 'https://plantdisease-e827d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNimQqfcuqd7qTnRIU_GCN12HlnaT9F5c',
    appId: '1:317214982580:android:b5cdc69e7eca00ab1172e1',
    messagingSenderId: '317214982580',
    projectId: 'plantdisease-e827d',
    storageBucket: 'plantdisease-e827d.firebasestorage.app',
    databaseURL: 'https://plantdisease-e827d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOz1ny5P_LufJZjnn4H6z55xfbs5LSiI',
    appId: '1:317214982580:ios:96ef84a94a73dcce1172e1',
    messagingSenderId: '317214982580',
    projectId: 'plantdisease-e827d',
    storageBucket: 'plantdisease-e827d.firebasestorage.app',
    databaseURL: 'https://plantdisease-e827d-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.farmTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOz1ny5P_LufJZjnn4H6z55xfbs5LSiI',
    appId: '1:317214982580:ios:96ef84a94a73dcce1172e1',
    messagingSenderId: '317214982580',
    projectId: 'plantdisease-e827d',
    storageBucket: 'plantdisease-e827d.firebasestorage.app',
    databaseURL: 'https://plantdisease-e827d-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.farmTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3eteFOnIkiuByIRkYe97WbzWwYXXp3YU',
    appId: '1:317214982580:web:e2490d8f89bc2bb51172e1',
    messagingSenderId: '317214982580',
    projectId: 'plantdisease-e827d',
    authDomain: 'plantdisease-e827d.firebaseapp.com',
    storageBucket: 'plantdisease-e827d.firebasestorage.app',
    measurementId: 'G-XKD4DREZV7',
    databaseURL: 'https://plantdisease-e827d-default-rtdb.firebaseio.com',
  );
}
